### ISSUE TITLE
crashes when default values are used

### ISSUE THREAD

**Issue by markstos** [grtcdr/acfc#2]
```
python3 -m acfc ~/.config/alacritty/alacritty.yml
Traceback (most recent call last):
  File "/home/mark/.local/lib/python3.10/site-packages/acfc/colors.py", line 70, in __init__
    _dict['colors']['selection']['background'])
KeyError: 'selection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/mark/.local/lib/python3.10/site-packages/acfc/__main__.py", line 49, in <module>
    main()
  File "/home/mark/.local/lib/python3.10/site-packages/acfc/__main__.py", line 41, in main
    colors = Colors(yaml.safe_load(stream)).as_foot(config)
  File "/home/mark/.local/lib/python3.10/site-packages/acfc/colors.py", line 76, in __init__
    raise Exception(
Exception: This configuration file does not set some required keys.
```

**Comment by grtcdr** [comment]
I've been working on improving the transition between YAML and INI to loosen the restrictions that currently exist, there's a missing option (colors.selection.background) that is causing this to happen.

**Comment by markstos** [comment]
Thanks for looking at this. 

It should not be required to specify the selection foreground and background, as both Alacritty and Foot have the same sensible default, which is to the invert the foreground and background colors. 

Note there's a conversation happening about the color configuration in foot that you may be interested in: https://codeberg.org/dnkl/foot/pulls/892

It started out as a pull request to document the color names of foot's color config syntax, then moved into discussion about whether foot should switch to naming the colors in the configuration like Alacritty does.

**Comment by grtcdr** [comment]
> It should not be required to specify the selection foreground and background, as both Alacritty and Foot have the same sensible default, which is to the invert the foreground and background colors.

Yeah, one of the recent commits addresses this by ignoring (and not printing) options that aren't specified, which leaves it to Foot to handle as you said.

> Note there's a conversation happening about the color configuration in foot that you may be interested in: https://codeberg.org/dnkl/foot/pulls/892

Thanks for bringing this to my attention, I wouldn't have written acfc if Foot used sensible names, but I guess they are sensible if you can memorize all the numbers, which is a chore. I hope they proceed with your suggestion.

**Comment by markstos** [comment]
I found that foot includes the color names as comments in the shipped `ini` file, but having sensible names as the config keys would be even better.

**Comment by markstos** [comment]
I see the recent commits-- thanks for those!

**Comment by grtcdr** [comment]
> I found that foot includes the color names as comments in the shipped ini file

That is true, but I always strip out comments from my dotfiles.

> I see the recent commits-- thanks for those!

My pleasure, I'll publish a new version soon.

**Comment by grtcdr** [comment]
Heads up, I'm rewriting acfc in Rust. I just can't work with Python and its ecosystem.

I do however have much bigger plans for the project, so it won't be a "use once and uninstall" type of program.

**Comment by markstos** [comment]
Woo! Checking it out.
